#!/usr/bin/env node
/*
 * Bundles the Vercel Functions from src/server into api/*.js.
 *
 *   node scripts/build-api.mjs           write the bundles
 *   node scripts/build-api.mjs --check   fail if a committed bundle is stale
 *
 * The bundles are committed: Vercel then deploys plain ES modules and never
 * has to compile this repo's TypeScript (whose tsconfig is set up for Vite).
 */
import { buildSync } from 'esbuild';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const FUNCTIONS = { leaderboard: 'src/server/leaderboardRoute.ts' };
const check = process.argv.includes('--check');
let stale = 0;

for (const [name, entry] of Object.entries(FUNCTIONS)) {
  const result = buildSync({
    entryPoints: [join(root, entry)],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node18',
    write: false,
    legalComments: 'none',
    logLevel: 'warning',
  });
  const code = `// GENERATED by scripts/build-api.mjs from ${entry} — do not edit.\n${result.outputFiles[0].text}`;
  const out = join(root, 'api', `${name}.js`);
  if (check) {
    if (!existsSync(out) || readFileSync(out, 'utf8') !== code) {
      console.error(`api/${name}.js is stale: run node scripts/build-api.mjs`);
      stale++;
    }
  } else {
    writeFileSync(out, code);
    console.log(`api/${name}.js ${(code.length / 1024).toFixed(1)} KB`);
  }
}
if (stale) process.exit(1);
